CREATE TABLE `salesforce_contract_contract_data`
(
  `ContractNumber`                   int(16) NOT NULL,
  `AccountID`                        int(12) NOT NULL,
  `ActivatedDate`                    datetime DEFAULT NULL,
  `LastActivityDate`                 date DEFAULT NULL,
  `StartDate`                        date DEFAULT NULL,
  `EndDate`                          date DEFAULT NULL,
  `ContractTerm`                     int(3) DEFAULT NULL,
  `Status`                           varchar(20) DEFAULT NULL,
  `StatusCode`                       varchar(20) DEFAULT NULL,
  `ShippingAddress`                  int(12) DEFAULT NULL,
  `ShippingCity`                     varchar(40) DEFAULT NULL,
  `ShippingCountry`                  varchar(40) DEFAULT NULL,
  `ShippingCountryCode`              varchar(3) DEFAULT NULL,
  `ShippingLatitude`                 float(19) DEFAULT NULL,
  `ShippingLongitude`                float(20) DEFAULT NULL,
  `ShippingPostalCode`               varchar(20) DEFAULT NULL,
  `ShippingState`                    varchar(20) DEFAULT NULL,
  `ShippingStateCode`                varchar(3) DEFAULT NULL,
  `ShippingStreet`                   varchar(255) DEFAULT NULL,
  `Description`                      varchar(200) DEFAULT NULL,
  `ActivatedById`                    int(12) DEFAULT NULL,
  `CompanySignedId`                  int(12) NDEFAULTOT NULL,
  `CompanySignedDate`                date DEFAULT NULL,
  `CustomerSignedDate`               date DEFAULT NULL,
  `CustomerSignedId`                 int(16) DEFAULT NULL,
  `CustomerSignedTitle`              varchar(100) DEFAULT NULL,
  `IsDeleted`                        tinyint(1) DEFAULT NULL,
  `LastApprovedDate`                 datetime DEFAULT NULL,
  `LastReferencedDate`               date DEFAULT NULL,
  `LastViewedDate`                   date DEFAULT NULL,
  `OwnerExpirationNotice`            int(3) DEFAULT NULL,
  `OwnerId`                          int(12) DEFAULT NULL,
  `Pricebook2Id`                     varchar(40) DEFAULT NULL,
  `RecordTypeId`                     varchar(6) DEFAULT NULL,
  `BillingAddress`                   int(12) DEFAULT NULL,
  `BillingCity`                      varchar(40) DEFAULT NULL,
  `BillingCountry`                   varchar(80) DEFAULT NULL,
  `BillingCountryCode`               varchar(3) DEFAULT NULL,
  `BillingLatitude`                  float(19) DEFAULT NULL,
  `BillingLongitude`                 float(20) DEFAULT NULL,
  `BillingPostalCode`                varchar(20) DEFAULT NULL,
  `BillingState`                     varchar(80) DEFAULT NULL,
  `BillingStateCode`                 varchar(3) DEFAULT NULL,
  `BillingStreet`                    varchar(255) DEFAULT NULL,
  `SpecialTerms`                     varchar(20) DEFAULT NULL,
  
    PRIMARY KEY (`ContractNumber`,`AccountID`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
